server:
    port: 8122
spring:
    application:
        name: newbee-cloud-shopcart-service
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
            password: nacos
            username: nacos
